### ISSUE TITLE
Adding auto mode 

### ISSUE THREAD

**Issue by dajma00** [danroth27/Net8BlazorServer#1]
I was able to migrate my Blazor Server app from .NET7 to .NET8 and it works. I would like to further add auto mode to the project by adding a client project to this. Guidance on how to accomplish that would be appreciated. I think such a guide will be helpful to many developers who are migrating there .NET7 Blazor server apps to .NET8.

**Comment by danroth27** [comment]
Thanks for this feedback! I've opened https://github.com/dotnet/AspNetCore.Docs/issues/30471 to track adding this documentation.
