### ISSUE TITLE
Is there an alternative to _Host.cshtml.cs?

### ISSUE THREAD

**Issue by mrlife** [danroth27/Net8BlazorServer#2]
Hi Dan,

Thank you for this upgrade process. It works well. For step 3, is there a new way to handle code from Pages/_Host.cshtml.cs? I have used that to access the request header (HttpContext) values in Blazor apps prior to ASP.NET Core 8.

ref: https://github.com/danroth27/Net8BlazorServer/blob/main/README.md

**Comment by danroth27** [comment]
Hi @mrlife. In .NET 8 RC2 you will be able to access the `HttpContext` from App.razor as a cascading value like this:

```csharp
[CascadingParameter]
public HttpContext HttpContext { get; set; }
```

In .NET 8 RC1 you can use the [`HttpContext` accessor service](https://learn.microsoft.com/aspnet/core/fundamentals/http-context#access-httpcontext-from-custom-components) from static server components as a temporary workaround.

**Comment by mrlife** [comment]
Thank you very much, this is great!

Per docs issue, adding the following: cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30575

**Comment by guardrex** [comment]
Thx @mrlife ... I'll get it tracked.
